Трущелев Михаил АПО-31 tg: @ThePsina
VictoriaOtm/qa-units-2021-1 pull request #22
Opened 2021-03-11 18:15 UTC by ThePsina

2021-03-11 18:28 UTC, mark-by requested changes
Разнести на отдельные кейсы стоит, наверное разные функции в sortOrders

2021-03-11 18:28 UTC, mark-by commented on src/utils/sortOrders.test.js
> +	})
в отдельный кейс вынести бы (describe)

2021-03-11 18:57 UTC, timofef commented on src/utils/sortOrders.test.js
> +	})
Сделай числа в date по-проще, а то не всегда сразу понятно, что больше, что меньше

2021-03-11 19:03 UTC, timofef commented on src/utils/sortOrders.test.js
> +});
Надо бы добавить проверки на null аргументы и случай, когда второй аргумент не функция

2021-03-11 19:30 UTC, timofef approved these changes
Аппрув

2021-03-12 05:57 UTC, mark-by approved these changes
yep

2021-03-12 11:49 UTC, VictoriaOtm commented on src/Order/__snapshots__/Order.test.js.snap
> +exports[`Order.js render without shop 1`] = `""`;
лучше в самом тесте проверять, что полученный wrapper === null, чем пустой снапшот писать

2021-03-12 11:51 UTC, VictoriaOtm commented on src/utils/sortOrders.test.js
> +		jest.resetAllMocks();
а зачем? у тебя каждый мок создается в тесте и везде свой используется. Эта очистка имеет смысл, если ты мок в beforeEach создаешь (так кстати имеет смысл делать, чтобы в каждом тесте не копипастить его)

2021-03-12 20:07 UTC, closed without merging