Выполнить задание
VictoriaOtm/qa-units-2021-1 pull request #31
Opened 2021-03-11 18:43 UTC by SanSanchezzz

2021-03-11 21:36 UTC, Arugaf requested changes

2021-03-11 21:36 UTC, Arugaf commented on src/Order/Order.test.js
> +    expect(getDate).toHaveBeenCalledTimes(0);
Кажется, что по названию тест проверяет какую-то одну конкретную вещь, а на деле еще чекает вызов вложенной функции.

2021-03-11 21:36 UTC, Arugaf commented on src/Order/Order.test.js
> +  it('getDate has been called', () => {
Одинаковое название тестов.

2021-03-11 21:36 UTC, Arugaf commented on src/Order/Order.test.js
> +    const order = fakeOrders[0];
Зачем здесь неиспользуемый объект?

2021-03-11 21:36 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	});
Ощущение, что может возникнуть коллизия с кейсом, когда объект null.

2021-03-11 21:36 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	});
Мне кажется стоило бы проверить еще и те кейсы, когда лишь в одном из объектов items === null.

2021-03-11 21:36 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	});
Аналогично.

2021-03-11 21:36 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +			date: 1552481120000,
Кинув быстрый взгляд сложно понять что должно быть больше, а что меньше.

2021-03-11 21:36 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	it('orders are null', () => {
Некорректное название теста.

2021-03-12 06:33 UTC, Kudesnjk commented on src/Order/Order.test.js
> +    const order = fakeOrders[0];
Объект не используется

2021-03-12 06:36 UTC, Kudesnjk commented on src/utils/sortOrders.test.js
> +			date: 1544356800000,
Может выбрать значения поменьше?

2021-03-12 06:36 UTC, Kudesnjk commented on src/utils/sortOrders.test.js
> +			date: 1552481120000,
Аналогично с предыдущем комментом

2021-03-12 06:36 UTC, Kudesnjk commented on src/utils/sortOrders.test.js
> +			date: 1552481120000,
Аналогично

2021-03-12 06:38 UTC, Kudesnjk commented on src/utils/sortOrders.test.js
> +	it('orders are null', () => {
можно поменять название теста, тк первый называется "callback has been called", например, на "callback has not been called"

2021-03-12 06:38 UTC, Kudesnjk commented on src/utils/sortOrders.test.js
> +});
\n в конце файла

2021-03-12 14:20 UTC, Kudesnjk commented on src/Order/Order.test.js
> +    expect(wrapper).toMatchSnapshot();
надо разбить проверки на 2 теста, 1 тест - 1 expect

2021-03-12 14:20 UTC, Kudesnjk commented on src/Order/Order.test.js
> +    expect(wrapper).toMatchSnapshot();
аналогично

2021-03-12 14:21 UTC, Kudesnjk commented on src/Order/Order.test.js
> +    expect(wrapper).toMatchSnapshot();
аналогично

2021-03-12 14:39 UTC, Arugaf commented
LGTM.

2021-03-12 20:22 UTC, VictoriaOtm commented on src/Order/__snapshots__/Order.test.js.snap
> +exports[`Order.js render with shop and date are null 1`] = `""`;
пустой снапшот получается, лучше в коде теста проверять, что компонент null

2021-03-17 17:56 UTC, closed without merging