Болгова Анастасия
VictoriaOtm/qa-units-2021-1 pull request #34
Opened 2021-03-11 18:54 UTC by shysa

2021-03-11 21:43 UTC, Arugaf requested changes

2021-03-11 21:43 UTC, Arugaf commented on src/Order/Order.test.js
> +  it('check null props', () => {
Props вроде как и не null.

2021-03-11 21:43 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	})
Такое оформление тестов как по мне очень сложно воспринимается. .each больше смысла использовать для однотипных данных. Тут же формат совсем разный, название теста воспринимается только после второго прочтения.

2021-03-11 21:43 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +	})
Аналогично.

2021-03-11 21:43 UTC, Arugaf commented on src/utils/sortOrders.test.js
> +		sortOrders([{items: ['1']}, {items: ['1', '2']}], mockSortFunc)
Почти везде аргументы передаются анонимно. Стоит вынести создаваемые объекты в отдельные переменные, чтобы проще было воспринимать.

2021-03-11 21:51 UTC, Dellvin reviewed
Все топ, не обращай внимание)

2021-03-11 21:51 UTC, Dellvin commented on src/Order/Order.test.js
> +    const testComponent = shallow(<Order order={{shop: 'test shop', date: getDate(), items: null}} />);
Объект в строчку не комильфо) и в date не надо передавать getDate, так как туда должна попадать число, а не строку

2021-03-11 21:51 UTC, Dellvin commented on src/utils/sortOrders.test.js
> +		expect(result).toEqual(0);
Для чисел подойдет и toBe()

2021-03-12 10:51 UTC, Arugaf commented
LGTM.

2021-03-12 19:10 UTC, closed without merging